// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Call.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * upanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * scrolldot_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_img_phone_png);    // assets/phone.png
LV_IMG_DECLARE(ui_img_avatar_png);    // assets/avatar.png

// FONTS
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
